export const DEFAULT_THEME_STATE = {
  background: "",
  foreground: "",
  card: "",
  card_foreground: "",
  popover: "",
  popover_foreground: "",
  primary: "",
  primary_foreground: "",
  secondary: "",
  secondary_foreground: "",
  muted: "",
  muted_foreground: "",
  accent: "",
  accent_foreground: "",
  destructive: "",
  destructive_foreground: "",
  border: "",
  input: "",
  ring: "",

  radius: "",
};

export const STORE_TO_CSS_VARS_MAPPING = {
  background: "--background",
  foreground: "--foreground",
  card: "--card",
  card_foreground: "--card-foreground",
  popover: "--popover",
  popover_foreground: "--popover-foreground",
  primary: "--primary",
  primary_foreground: "--primary-foreground",
  secondary: "--secondary",
  secondary_foreground: "--secondary-foreground",
  muted: "--muted",
  muted_foreground: "--muted-foreground",
  accent: "--accent",
  accent_foreground: "--accent-foreground",
  destructive: "--destructive",
  destructive_foreground: "--destructive-foreground",
  border: "--border",
  input: "--input",
  ring: "--ring",

  radius: "--radius",
};
